[window]
startup_mode = "Maximized"
dynamic_padding = false

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 0
y = 8

[font]
normal = { family = "LiterationMono Nerd Font", style = "Regular" }
bold = { family = "LiterationMono Nerd Font", style = "Bold" }
italic = { family = "LiterationMono Nerd Font", style = "Italic" }
bold_italic = { family = "LiterationMono Nerd Font", style = "Bold Italic" }
size = 10.0

[colors.primary]
foreground = "#a2adc3"
background = "#2c2d30"

[colors.cursor]
text = "#303847"
cursor = "#dfe3ec"

[colors.normal]
black = "#2c2d30"
red = "#bf8079"
green = "#829d7a"
yellow = "#ac976c"
blue = "#7c98bf"
magenta = "#b089aa"
cyan = "#699f9e"
white = "#a2adc3"

[colors.bright]
black = "#4e5d73"
red = "#a7554b"
green = "#597e41"
yellow = "#887129"
blue = "#4379c0"
magenta = "#965e98"
cyan = "#488384"
white = "#f1f3f7"

